# -*- coding: utf-8 -*-
"""Teste Unitário para Agendamento (RF03)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJuVKD2PS7FmAftTG0Cgj4DdEkRdGY02
"""

# Arquivo: unit_test_example.py
# Exemplo de Teste Unitário usando a biblioteca 'unittest' para validar a Regra de Negócio RF03.
# O foco é testar a lógica da função 'agendar_consulta' em isolamento.

import unittest
from datetime import datetime, timedelta
# Importamos a função de backend (a "unidade" de código a ser testada)
from implementation_prototype import agendar_consulta, MOCK_AGENDA

class TestAgendamentoVidaPlus(unittest.TestCase):
    """
    Classe de Testes Unitários para a Regra de Negócio de Agendamento.
    """

    # Médico e horário de teste padrão
    TEST_MEDICO = "M999"
    HORARIO_BASE = datetime(2026, 1, 15, 9, 0)
    DURACAO = 60

    def setUp(self):
        """
        Configura o ambiente antes de cada teste.
        Garante que o médico de teste comece com uma agenda limpa (isolamento).
        """
        # Remove a agenda do médico de teste, se existir, para isolar os testes.
        if self.TEST_MEDICO in MOCK_AGENDA:
            del MOCK_AGENDA[self.TEST_MEDICO]

        # Cria um agendamento inicial para simular uma agenda ocupada
        # Agendamento Ocupado: 09:00 - 10:00
        agendar_consulta(
            self.TEST_MEDICO,
            self.HORARIO_BASE,
            self.DURACAO
        )

    # --- CTF01: Cenário de Falha (Conflito de Horário) ---
    def test_01_agendamento_em_conflito_deve_falhar(self):
        """
        CTF01 (Cenário de Falha): Tentar agendar uma consulta em um horário
        que se sobrepõe ao agendamento inicial (9:30 AM).
        """
        print("\n[Cenário de Teste Unitário 01 - Falha Esperada]")

        # Horário que cai dentro do agendamento 09:00 - 10:00
        horario_conflito = self.HORARIO_BASE + timedelta(minutes=30)

        # A asserção verifica se o resultado da função é 'False' (FALHA)
        resultado = agendar_consulta(self.TEST_MEDICO, horario_conflito)

        # self.assertFalse() verifica se a função retornou o valor booleano 'False'
        self.assertFalse(resultado, "A função deveria ter retornado FALSO para o conflito.")

    # --- CTF02: Cenário de Sucesso ---
    def test_02_agendamento_em_horario_livre_deve_ser_registrado(self):
        """
        Cenário de Sucesso: Tentar agendar uma consulta após o término
        do agendamento inicial (10:00 AM).
        """
        print("\n[Cenário de Teste Unitário 02 - Sucesso Esperado]")

        # Horário que começa exatamente onde o outro termina: 10:00 AM
        horario_livre = self.HORARIO_BASE + timedelta(minutes=self.DURACAO)

        # A asserção verifica se o resultado da função é 'True' (SUCESSO)
        resultado = agendar_consulta(self.TEST_MEDICO, horario_livre)

        # self.assertTrue() verifica se a função retornou o valor booleano 'True'
        self.assertTrue(resultado, "A função deveria ter retornado VERDADEIRO para o horário livre.")

        # Asserção Adicional: Verificar se o novo agendamento foi realmente adicionado à MOCK_AGENDA
        self.assertEqual(len(MOCK_AGENDA[self.TEST_MEDICO]), 2, "O segundo agendamento deveria ter sido adicionado.")


# --- EXECUÇÃO DOS TESTES ---
if __name__ == '__main__':
    # Para rodar, você precisará dos dois arquivos (.py) na mesma pasta.
    unittest.main(argv=['first-arg-is-ignored'], exit=False)